apiVersion: v1
kind: Namespace
metadata:
  name: namespace-admin

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-admin-omniverse-viewer
  namespace: namespace-admin
  labels:
    app: deployment-admin-omniverse-viewer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployment-admin-omniverse-viewer
  template:
    metadata:
      labels:
        app: deployment-admin-omniverse-viewer
    spec:
      hostNetwork: true
      containers:
        - name: container-admin-kit-app
          image: dineshkrish93/dk-public-repo:kit-app-editor-1-streaming
          imagePullPolicy: IfNotPresent
          env:
            - name: NVIDIA_VISIBLE_DEVICES
              value: "all"
            - name: NVIDIA_DRIVER_CAPABILITIES
              value: "all"
            - name: NVDA_KIT_ARGS
              value: "--/exts/omni.kit.livestream.app/primaryStream/signalPort=49101 --/exts/omni.kit.livestream.app/primaryStream/streamPort=47999"
          resources:
            limits:
              nvidia.com/gpu: "1"
          volumeMounts:
            - name: dshm
              mountPath: /dev/shm

        - name: container-admin-web-viewer
          image: dineshkrish93/dk-public-repo:web-viewer-sample-1.5.2
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          env:
            - name: SIGNALING_PORT
              value: "49101"
            - name: WEB_PORT
              value: "8081"

      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: 4Gi

---
apiVersion: v1
kind: Service
metadata:
  name: service-admin-omniverse-viewer
  namespace: namespace-admin
  labels:
    app: deployment-admin-omniverse-viewer
spec:
  type: NodePort
  selector:
    app: deployment-admin-omniverse-viewer
  ports:
    - name: web-viewer
      port: 80
      targetPort: 8081
