apiVersion: apps/v1
kind: Deployment
metadata:
  name: omniverse-viewer
  labels:
    app: omniverse-viewer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: omniverse-viewer
  template:
    metadata:
      labels:
        app: omniverse-viewer
    spec:
      containers:
        - name: kit-app
          image: dineshkrish93/dk-public-repo:kit-app-editor-1-streaming
          env:
            - name: NVIDIA_VISIBLE_DEVICES
              value: "all"
            - name: NVIDIA_DRIVER_CAPABILITIES
              value: "all"
          resources:
            limits:
              nvidia.com/gpu: "1"
          volumeMounts:
            - name: dshm
              mountPath: /dev/shm

        - name: web-viewer
          image: dineshkrish93/dk-public-repo:web-viewer-sample-1.5.2
          ports:
            - containerPort: 80

      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: 4Gi

---
apiVersion: v1
kind: Service
metadata:
  name: omniverse-viewer
  labels:
    app: omniverse-viewer
spec:
  type: NodePort
  selector:
    app: omniverse-viewer
  ports:
    - name: web-viewer
      port: 80
      targetPort: 80
      nodePort: 30080
